### 배열의 연산: 행렬(matrix)의 연산, 선형대수(Linear Algebra)

### [1] 배열과 상수간의 연산 :  배열 <연산자> 상수, 상수 <연산자> 배열
#### 하나의 스칼라와 배열의 연산, 브로드 캐스팅에 해당

In [1]:
import numpy as np

In [2]:
A = np.arange(16).reshape(4,4)
print(A,A.shape)

print(A + 10)
print(A - 10)
print(A * 10)
print(A / 10)

print(10 + A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (4, 4)
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   0   1]
 [  2   3   4   5]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]]
[[0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]
 [0.8 0.9 1.  1.1]
 [1.2 1.3 1.4 1.5]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


### [2] 배열의 요소간의 연산 : element-wise 연산

In [3]:
# shape 이 같은 경우
A = np.arange(9).reshape(3,3)
B = np.arange(9).reshape(3,3) - 1
print(A)
print(B)

print(A + B)
print(A - B)
print(A * B)
print(A / B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  1  3]
 [ 5  7  9]
 [11 13 15]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 0  0  2]
 [ 6 12 20]
 [30 42 56]]
[[-0.                 inf  2.        ]
 [ 1.5         1.33333333  1.25      ]
 [ 1.2         1.16666667  1.14285714]]


C:\ProgramData\Anaconda3\envs\tf20\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


### [3] 브로드 캐스팅 : 차원의 크기가 서로 다른 배열에서 산술연산이 가능

In [4]:
A = np.arange(6).reshape(3,2) 
B = np.arange(2).reshape(1,2) + 1
print(A)  # (3,2)
print(B)  # (1,2)

print('-'*30)

print(A + B)
print(A - B)
print(A * B)
print(A / B)

[[0 1]
 [2 3]
 [4 5]]
[[1 2]]
------------------------------
[[1 3]
 [3 5]
 [5 7]]
[[-1 -1]
 [ 1  1]
 [ 3  3]]
[[ 0  2]
 [ 2  6]
 [ 4 10]]
[[0.  0.5]
 [2.  1.5]
 [4.  2.5]]


In [5]:
# 브로드 캐스팅 규칙 : 차원과 shape 이 자동 조정
# 규칙 1 : 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열의 shape의
#          앞쪽(왼쪽)을 1로 채운다
# 규칙 2 : 차원이 같은 두 배열의 shape 이 1인 배열을 다른 배열의 shape과 
#          일치하도록 늘인다
# 규칙 3 : 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생
A = np.ones((2,3))  # (2,3)
B = np.arange(3)    # (3,)
print(A)
print(B)

# 규칙 1 적용 : B.shape ==> (1,3)    [[0 1 2]]
# 규칙 2 적용 : B.shape ==> (2,3)    [[0 1 2]
#                                    [0 1 2]]
print(A + B)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [6]:
A = np.ones((3,1))  # (3,1)
B = np.arange(3)    # (3,)
print(A)
print(B)
# 규칙 1 적용 : B.shape b ==> (1,3)    [[0 1 2]]
# 규칙 2 적용 : B.shape b ==> (3,3)    [[0 1 2]
#                                       [0 1 2]
#                                       [0 1 2]]
# 규칙 2 적용 : A.shape b ==> (3,3)    [[1 1 1]
#                                       [1 1 1]
#                                       [1 1 1]]  
print(A + B)   # (3,3)

[[1.]
 [1.]
 [1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [7]:
A = np.ones((3,2))  # (3,2)
B = np.arange(3)    # (3,)
print(A)
print(B)


# 규칙 1 적용 : B.shape b ==> (1,3)    [[0 1 2]]
# 규칙 2 적용 : B.shape b ==> (3,3)    [[0 1 2]
#                                       [0 1 2]
#                                       [0 1 2]]
# 규칙 3 에 해당하므로 오류 발생
# print(A + B)  # ValueError

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


In [9]:
# 끝쪽 차원부터 비교하면서 앞쪽으로 진행한다
# 두 배열의 각 차원에서 shape 이 같거나 shape이 1인경우 브로드캐스팅 가능
# A  =  (2, 3)
# B  =     (3,)
# ----------------
# 결과: (2, 3)

# A  =  (3, 1)
# B  =     (3,)
# ----------------
# 결과: (3, 3)

# A  =  (3, 2)
# B  =     (3,)
# ----------------
# 결과: (3, x)  ==> 오류
    
# A  =  (15, 3, 5)
# B  =      (3, 1)
# ----------------
# 결과: (15, 3, 5)

# A  =  (8, 1, 6, 1)
# B  =     (7, 1, 5)
# --------------------
# 결과: (8 ,7, 6 ,5)
    
# A  =  (8, 4, 3)
# B  =     (2, 1)
# ----------------
# 결과: (8, x, 3) ==> 오류   
    

### [4] dot product: 내적 곱셈 ,행렬(matrix) 곱셈

In [20]:
# 1차원 배열(벡터)의 내적
A = np.array([1,2,3])
B = np.array([4,5,6])
print(A,A.shape)
print(B,B.shape)

print(A*B)   # element-wise 곱셈

dot_product = np.dot(A,B)  # 내적 곱셈
print(dot_product)
print(A[0]*B[0] + A[1]*B[1] + A[2]*B[2])

[1 2 3] (3,)
[4 5 6] (3,)
[ 4 10 18]
32
32


In [28]:
# 2차원 배열(행렬,matrix)의 곱셈
A = np.arange(1,7).reshape(2,3)
B = np.arange(7,13).reshape(3,2)
print(A)    # (2,3)
print(B)    # (3,2)

# print(A*B)  # ValueError

dot_product = np.dot(A,B)  # 내적 곱셈
print(dot_product)

print(np.matmul(A,B))  # 동일한 결과
# (2,3) * (3,2) = (2,2)
# (m,n) * (n,l) = (m,l) # 행렬의 내적 곱셈시 shape 공식, 필수 암기 요망!!

# (10,4) * (x,y) = (10,2) #  x = 4, y = 2를 구할 수 있어야한다

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
[[ 58  64]
 [139 154]]
[[ 58  64]
 [139 154]]


In [23]:
A = np.mat("1 2 3;4 5 6")
B = np.mat("7 8;9 10;11 12")
print(A)
print(B)
print(type(A))
print(A*B)  # 내적 곱셈

[[1 2 3]
 [4 5 6]]
[[ 7  8]
 [ 9 10]
 [11 12]]
<class 'numpy.matrix'>
[[ 58  64]
 [139 154]]


In [26]:
## 선형 방정식 풀이 : 선형시스템을 해석
A = np.mat("1 -2 1;0 2 -8;-4 5 9")
print("A:",A)
b = np.array([0,8,-9])
print(b)

# 연립방정식
# 1*x0 - 2*x1 + 1*x2 = 0    # 29 - 32 + 3 = 0
# 0*x0 + 2*x1 - 8*x2 = 8
# -4*x0 + 5*x1 + 9*x2 = -9

A: [[ 1 -2  1]
 [ 0  2 -8]
 [-4  5  9]]
[ 0  8 -9]


In [27]:
x = np.linalg.solve(A,b)
print('Solution:',x)
print('Check\n',np.dot(A,x))

# A dot x ==> b
# [[ 1 -2  1]         [[29          [[0
#  [ 0  2 -8]     dot   16      ==>   8
#  [-4  5  9]]          3]]           9]]
#  (3,3) * (3,1) ==> (3,1) 

Solution: [29. 16.  3.]
Check
 [[ 0.  8. -9.]]


In [37]:
# 기타 연산자 : zeros(), ones()
a = np.zeros(10)   # 초기 값을 0으로 채워서 배열을 생성
print(a)

a = np.zeros((3,4))
print(a)

a = np.ones(10)
print(a)

a = np.ones((3,4))  # 초기 값을 1으로 채워서 배열을 생성
print(a)

e = np.empty((10,3)) # 초기 값을 설정하지 않고 배열을 생성, 빠르게 생성
print(e)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[ 1.42200269e-311  9.58487353e-322  0.00000000e+000]
 [ 0.00000000e+000  1.42173718e-311  5.02034658e+175]
 [ 1.27092332e-075  3.06059609e-057  2.94879478e+179]
 [ 7.31556606e+169  1.47763641e+248  1.16096346e-028]
 [ 7.69165785e+218  1.35617292e+248  3.10139001e+179]
 [ 1.17687803e-047  2.08934532e-076  6.12674575e-062]
 [ 4.30348039e-096  6.32299154e+233  6.48224638e+170]
 [ 5.22411352e+257  5.74020278e+180  8.37174974e-144]
 [ 1.41529402e+161  6.00736899e-067  4.52576983e+097]
 [ 5.06266576e-038  3.92417332e+126 -2.40197436e+173]]


In [48]:
# numpy 난수 발생
# rand() : 실수
# randint() : 정수
# randn() : 실수, 정규 분포(standard normal distribution)

np.random.seed(5)  # 난수의 씨앗
print(np.random.rand(3,4)) # 값이 0 ~ 1 사이, shape (3,4)
print(np.random.randint(10,size=(3,4))) # 값이 0 ~ 10 사이, shape (3,4)
print(np.random.randn(3,4)) # 정규 분포, 값이 0 ~ 1 사이, shape (3,4)

[[0.22199317 0.87073231 0.20671916 0.91861091]
 [0.48841119 0.61174386 0.76590786 0.51841799]
 [0.2968005  0.18772123 0.08074127 0.7384403 ]]
[[1 4 6 2]
 [9 9 9 9]
 [1 2 7 0]]
[[ 0.07453116  0.55653535  1.97258009 -0.24106628]
 [ 0.36337589  1.07448417 -1.99994678  0.95853877]
 [ 0.94220227  0.5689886   0.92890695  1.22638799]]
