### 배열의 연산: 행렬(matrix)의 연산, 선형대수(Linear Algebra)

### [1] 배열과 상수간의 연산 :  배열 <연산자> 상수, 상수 <연산자> 배열
#### 하나의 스칼라와 배열의 연산, 브로드 캐스팅에 해당

In [1]:
import numpy as np

In [5]:
A = np.arange(16).reshape(4,4)
print(A,A.shape)

print(A + 10)
print(A - 10)
print(A * 10)
print(A / 10)

print(10 + A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] (4, 4)
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]
[[-10  -9  -8  -7]
 [ -6  -5  -4  -3]
 [ -2  -1   0   1]
 [  2   3   4   5]]
[[  0  10  20  30]
 [ 40  50  60  70]
 [ 80  90 100 110]
 [120 130 140 150]]
[[0.  0.1 0.2 0.3]
 [0.4 0.5 0.6 0.7]
 [0.8 0.9 1.  1.1]
 [1.2 1.3 1.4 1.5]]
[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]]


### [2] 배열의 요소간의 연산 : element-wise 연산

In [11]:
A = np.arange(9).reshape(3,3)
B = np.arange(9).reshape(3,3) - 1
print(A)
print(B)

print(A + B)
print(A - B)
print(A * B)
print(A / B)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[-1  1  3]
 [ 5  7  9]
 [11 13 15]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[ 0  0  2]
 [ 6 12 20]
 [30 42 56]]
[[-0.                 inf  2.        ]
 [ 1.5         1.33333333  1.25      ]
 [ 1.2         1.16666667  1.14285714]]


C:\ProgramData\Anaconda3\envs\tf20\lib\site-packages\ipykernel_launcher.py:9: RuntimeWarning: divide by zero encountered in true_divide
  if __name__ == '__main__':


### [3] 브로드 캐스팅 : 차원의 크기가 서로 다른 배열에서 산술연산이 가능

In [17]:
A = np.arange(6).reshape(3,2) 
B = np.arange(2).reshape(1,2) + 1
print(A)  # (3,2)
print(B)  # (1,2)

print('-'*30)

print(A + B)
print(A - B)
print(A * B)
print(A / B)

[[0 1]
 [2 3]
 [4 5]]
[[1 2]]
------------------------------
[[1 3]
 [3 5]
 [5 7]]
[[-1 -1]
 [ 1  1]
 [ 3  3]]
[[ 0  2]
 [ 2  6]
 [ 4 10]]
[[0.  0.5]
 [2.  1.5]
 [4.  2.5]]


In [23]:
# 브로드 캐스팅 규칙 : 차원과 shape 이 자동 조정
# 규칙 1 : 두 배열의 차원 수가 다르면 더 작은 수의 차원을 가진 배열의 shape의
#          앞쪽(왼쪽)을 1로 채운다
# 규칙 2 : 차원이 같은 두 배열의 shape 이 1인 배열을 다른 배열의 shape과 
#          일치하도록 늘인다
# 규칙 3 : 임의의 차원에서 크기가 일치하지 않고 1도 아니라면 오류가 발생
A = np.ones((2,3))  # (2,3)
B = np.arange(3)    # (3,)
print(A)
print(B)

# 규칙 1 적용 : B.shape ==> (1,3)    [[0 1 2]]
# 규칙 2 적용 : B.shape ==> (2,3)    [[0 1 2]
#                                    [0 1 2]]
print(A + B)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]]


In [26]:
A = np.ones((3,1))  # (3,1)
B = np.arange(3)    # (3,)
print(A)
print(B)
# 규칙 1 적용 : B.shape b ==> (1,3)    [[0 1 2]]
# 규칙 2 적용 : B.shape b ==> (3,3)    [[0 1 2]
#                                       [0 1 2]
#                                       [0 1 2]]
# 규칙 2 적용 : A.shape b ==> (3,3)    [[1 1 1]
#                                       [1 1 1]
#                                       [1 1 1]]  
print(A + B)   # (3,3)

[[1.]
 [1.]
 [1.]]
[0 1 2]
[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


In [28]:
A = np.ones((3,2))  # (3,2)
B = np.arange(3)    # (3,)
print(A)
print(B)


# 규칙 1 적용 : B.shape b ==> (1,3)    [[0 1 2]]
# 규칙 2 적용 : B.shape b ==> (3,3)    [[0 1 2]
#                                       [0 1 2]
#                                       [0 1 2]]
# 규칙 3 에 해당하므로 오류 발생
# print(A + B)  # ValueError

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


In [ ]:
# 끝쪽 차원부터 비교하면서 앞쪽으로 진행한다
# 두 배열의 각 차원에서 shape 이 같거나 shape이 1인경우 브로드캐스팅 가능
A  =  (2, 3)
B  =     (3,)
----------------
결과: (2, 3)

A  =  (3, 1)
B  =     (3,)
----------------
결과: (3, 3)

A  =  (3, 2)
B  =     (3,)
----------------
결과: (3, x)  ==> 오류
    
A  =  (15, 3, 5)
B  =      (3, 1)
----------------
결과: (15, 3, 5)

A  =  (8, 1, 6, 1)
B  =     (7, 1, 5)
--------------------
결과: (8 ,7, 6 ,5)
    
A  =  (8, 4, 3)
B  =     (2, 1)
----------------
결과: (8, x, 3) ==> 오류   
    