## multi-classification
: multi-nomial classification (다중 분류) : Y값의 범주가 3개 이상인 분류
#### 활성화 함수(Activation function) 으로 softmax함수 가 사용된다

In [1]:
import tensorflow as tf
import numpy as np
tf.random.set_seed(5)

In [3]:
# train data set :
# x_data :  [N,4]  --> [8,4]
x_data = [[1,2,1,1],
          [2,1,3,2],
          [3,1,3,4],
          [4,1,5,5],
          [1,7,5,5],
          [1,2,5,6],
          [1,6,6,6],
          [1,7,7,7]]

# y_data : [N,3] --> [8,3]
y_data = [[0,0,1],  # [2]
          [0,0,1],  # [2]
          [0,0,1],  # [2]
          [0,1,0],  # [1]
          [0,1,0],  # [1]
          [0,1,0],  # [1]
          [1,0,0],  # [0]
          [1,0,0]]  # [0]

x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)

In [4]:
nb_classes = 3 # 분류(class) 갯수

# 변수 초기화 : weight, bias
# (8,4) * (4,3) = (8,3)
W = tf.Variable(tf.random.normal([4,nb_classes]), name = 'weight')
b = tf.Variable(tf.random.normal([nb_classes]), name = 'bias')

In [5]:
# 예측 함수(hypothesis) : H(X) = softmax(X*W + b)
def logits(X):
    return tf.matmul(X,W) + b

def hypothesis(X):
    return tf.nn.softmax(logits(X))   

In [6]:
# # 비용 함수 구현 방법 1: log함수를 사용하여 수식을 직접 표현
# def cost_func():
#     cost = tf.reduce_mean(-tf.reduce_sum(y_train*tf.math.log(hypothesis(x_train)),
#                                          axis=1))
#     return cost

In [7]:
# 비용함수 구현 방법 2 : tf.nn.softmax_cross_entropy_with_logits() 함수 사용
def cost_func():
    cost_i = tf.nn.softmax_cross_entropy_with_logits(logits = logits(x_train),
                                             labels = y_train)
    cost =  tf.reduce_mean(cost_i)
    return cost

In [8]:
# 경사 하강법
# learning_rate(학습율)을 0.01 로 설정하여 optimizer객체를 생성
optimizer = tf.keras.optimizers.Adam(lr=0.01)

In [9]:
# 학습 시작
print('****** Start Learning!!')
for step in range(5001):
    # cost를 minimize 한다
    optimizer.minimize(cost_func,var_list=[W,b]) # W,b를 업데이트
    if step % 100 == 0:
        print('%04d'%step,'cost:[',cost_func().numpy(),']',
             ' W:',W.numpy(),' b:',b.numpy())
        
print('****** Learning Finished!!') 

****** Start Learning!!
0000 cost:[ 5.9294786 ]  W: [[-0.17030679 -0.94028634 -0.04964045]
 [-0.7325406   1.3331522  -0.628548  ]
 [ 0.86406636 -0.07899956  2.4388697 ]
 [ 0.77250797  1.2759615   0.9701489 ]]  b: [0.2365285  0.8206551  0.73660946]
0100 cost:[ 1.1552231 ]  W: [[-0.5470718  -0.03807735 -0.24936767]
 [-0.02111381  0.53332376 -0.75196683]
 [ 1.3003658   0.11232628  2.0026753 ]
 [ 1.1551087   1.6565033   0.5315274 ]]  b: [0.28334293 0.65043896 0.8277265 ]
0200 cost:[ 0.67908156 ]  W: [[-0.91939455  0.13888852  0.01354875]
 [ 0.17423075  0.14159855 -0.43874633]
 [ 1.3674178   0.38877195  1.8341357 ]
 [ 1.1541306   1.932615    0.42247915]]  b: [-0.11689189 -0.17410971  1.5440289 ]
0300 cost:[ 0.55539304 ]  W: [[-1.1160616   0.1323512   0.25641182]
 [ 0.1963242   0.04641756 -0.3066862 ]
 [ 1.4728361   0.5946489   1.6559124 ]
 [ 1.2038623   1.9983065   0.3519727 ]]  b: [-0.4423253 -0.716647   2.0596278]
0400 cost:[ 0.4929726 ]  W: [[-1.2841822   0.1575776   0.43241403]
 [ 0.183

3600 cost:[ 0.06385824 ]  W: [[-6.0440283   2.6351087   3.7329879 ]
 [-0.09549897  0.10010631  0.21261844]
 [ 5.6247296   0.44535246 -2.1916685 ]
 [ 0.52309287  2.2213547   0.8669257 ]]  b: [-10.70105   -1.369114  11.19566 ]
3700 cost:[ 0.06040318 ]  W: [[-6.176277    2.7121787   3.8184495 ]
 [-0.10405619  0.10523541  0.2211667 ]
 [ 5.748734    0.4033722  -2.2929323 ]
 [ 0.48644093  2.2489507   0.8884058 ]]  b: [-10.963928   -1.3690696  11.427615 ]
3800 cost:[ 0.057148032 ]  W: [[-6.307857    2.7889762   3.9034507 ]
 [-0.11259708  0.11036908  0.22967245]
 [ 5.872369    0.36126044 -2.3938372 ]
 [ 0.44958264  2.276545    0.9100709 ]]  b: [-11.224799   -1.3686513  11.657841 ]
3900 cost:[ 0.05407995 ]  W: [[-6.4387984   2.865511    3.988019  ]
 [-0.12112138  0.11550506  0.23813862]
 [ 5.99564     0.3190506  -2.494397  ]
 [ 0.41253898  2.304123    0.9319085 ]]  b: [-11.4837475  -1.367889   11.886414 ]
4000 cost:[ 0.05118698 ]  W: [[-6.569132    2.9417915   4.072178  ]
 [-0.12962751  0.12063

In [10]:
# Weight과 bias 출력
print('Weight:',W.numpy())  # (4,3)
print('bias:', b.numpy())   # (3,)

Weight: [[-7.8441830e+00  3.6925721e+00  4.8953791e+00]
 [-2.1366470e-01  1.7167602e-01  3.2927620e-01]
 [ 7.3285356e+00 -1.4589632e-01 -3.5808389e+00]
 [-2.5742422e-03  2.6041079e+00  1.1803545e+00]]
bias: [-14.22404    -1.3462191  14.310619 ]


In [11]:
# 예측
# tf.argmax() : 값이 가장 큰 요소의 인덱스 값을 반환
def predict(X):
    return tf.argmax(hypothesis(X),axis=1)

# 학습 데이터를 검증 데이터로 동일하게 사용하는 경우
x_test = x_train
y_test = y_train

preds = predict(x_test)
print(preds.numpy())
print(hypothesis(x_test).numpy())
print(tf.argmax(y_test,1).numpy())

[2 2 2 1 1 1 0 0]
[[6.7201891e-15 4.4788094e-06 9.9999547e-01]
 [3.0885475e-11 6.2573748e-03 9.9374264e-01]
 [8.2859493e-18 3.1583805e-02 9.6841621e-01]
 [5.7242741e-16 9.7510344e-01 2.4896599e-02]
 [5.8690630e-02 9.3963599e-01 1.6734032e-03]
 [3.0668104e-02 9.6914285e-01 1.8900630e-04]
 [9.2271829e-01 7.7280879e-02 9.1235347e-07]
 [9.9905401e-01 9.4603549e-04 1.0147023e-10]]
[2 2 2 1 1 1 0 0]
