# Keras Basic
### * Sequential Layer 의 주요 레이어 정리 
#### [1]  Dense Layer : Fully Connected Layer, layer의 입력과 출력 사이에 있는 모든 뉴런이 서로 연결 되는 Layer
#### [2]  Flatten Layer : 다차원(4차원)을 2차원으로 축소하여 FC Layer에 전달한다
#### [3]  Conv2D Layer : 이미지 특징을 추출하는 Convolution Layer 
#### [4]  MaxPool2D Layer : 중요 데이터(값이 큰 데이터)를 subsampling 하는 Layer
#### [5]  Dropout Layer : 학습시 신경망의 과적합을 막기위해 일부 뉴런을 제거하는 Layer

#### https://greeksharifa.github.io/keras/2018/06/29/Keras-Tutorial/

### [1] Dense Layer

In [1]:
# keras_basic
import tensorflow as tf
import numpy as np

In [2]:
# keras 를 이용한 XOR 네트워크

# train data set 
x_data = [[0,0],
          [0,1],
          [1,0],
          [1,1]]   # (4,2)

y_data = [[0],
          [1],
          [1],
          [0]]     # (4,1)

x_train = np.array(x_data,dtype=np.float32)
y_train = np.array(y_data,dtype=np.float32)

In [3]:
# Dense Layer 구현
model = tf.keras.Sequential([
    #  (4,2) * (2,2) = (4,2)
    # unites : 뉴런의 갯수
    # Param : 6 (W:4, b:2), W = W의 shape 값의 곱, b = W의 컬럼의 갯수(2차원인 경우) 
    # 파라미터수: (입력측 뉴런의 수 + 1) * (출력측 뉴런의 수) = (2 + 1) * 2 = 6
    tf.keras.layers.Dense(units=2,activation='sigmoid',input_shape=(2,)),
    
    #  (4,2) * (2,1) = (4,1)
    # Param : 3 (W:2, b:1), W = W의 shape 값의 곱, b = W의 컬럼의 갯수(2차원인 경우) 
    # 파라미터수:  (입력측 뉴런의 수 + 1) * (출력측 뉴런의 수) = (2 + 1) * 1 = 3
    tf.keras.layers.Dense(units=1,activation='sigmoid')                            
])

model.compile(optimizer = tf.keras.optimizers.Adam(lr=0.1),loss='mse',metrics=['accuracy'])
model.summary()  # 각 layer의 정보를 출력

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 2)                 6         
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 3         
Total params: 9
Trainable params: 9
Non-trainable params: 0
_________________________________________________________________


In [4]:
model.fit(x_train,y_train,epochs=1000,batch_size=1,verbose=1) # verbose=1, 메세지를 출력

Train on 4 samples
Epoch 1/1000
4/4 [==============================] - 0s 125ms/sample - loss: 0.3233 - accuracy: 0.5000
Epoch 2/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2749 - accuracy: 0.5000
Epoch 3/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2585 - accuracy: 0.5000
Epoch 4/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2511 - accuracy: 0.5000
Epoch 5/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2569 - accuracy: 0.2500
Epoch 6/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.2544 - accuracy: 0.5000
Epoch 7/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.2581 - accuracy: 0.5000
Epoch 8/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2562 - accuracy: 0.5000
Epoch 9/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.2556 - accuracy: 0.5000
Epoch 10/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.25

4/4 [==============================] - 0s 3ms/sample - loss: 0.1379 - accuracy: 0.7500
Epoch 82/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1378 - accuracy: 0.7500
Epoch 83/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1374 - accuracy: 0.7500
Epoch 84/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1378 - accuracy: 0.7500
Epoch 85/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1376 - accuracy: 0.7500
Epoch 86/1000
4/4 [==============================] - 0s 4ms/sample - loss: 0.1376 - accuracy: 0.7500
Epoch 87/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1356 - accuracy: 0.7500
Epoch 88/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1369 - accuracy: 0.7500
Epoch 89/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1351 - accuracy: 0.7500
Epoch 90/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1357 - accuracy: 0.7500
Epoc

4/4 [==============================] - 0s 1ms/sample - loss: 0.1295 - accuracy: 0.5000
Epoch 162/1000
4/4 [==============================] - 0s 3ms/sample - loss: 0.1292 - accuracy: 0.5000
Epoch 163/1000
4/4 [==============================] - 0s 3ms/sample - loss: 0.1293 - accuracy: 0.5000
Epoch 164/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1278 - accuracy: 0.7500
Epoch 165/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1292 - accuracy: 0.5000
Epoch 166/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1292 - accuracy: 0.5000
Epoch 167/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1287 - accuracy: 0.7500
Epoch 168/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1275 - accuracy: 0.7500
Epoch 169/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1275 - accuracy: 0.7500
Epoch 170/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1275 - accuracy: 0.

4/4 [==============================] - 0s 997us/sample - loss: 0.1285 - accuracy: 0.5000
Epoch 242/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1273 - accuracy: 0.7500
Epoch 243/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1266 - accuracy: 0.7500
Epoch 244/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1270 - accuracy: 0.7500
Epoch 245/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1270 - accuracy: 0.7500
Epoch 246/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1272 - accuracy: 0.7500
Epoch 247/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1280 - accuracy: 0.5000
Epoch 248/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1281 - accuracy: 0.5000
Epoch 249/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1288 - accuracy: 0.5000
Epoch 250/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1276 - accuracy: 

4/4 [==============================] - 0s 2ms/sample - loss: 0.1274 - accuracy: 0.5000
Epoch 322/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1264 - accuracy: 0.7500
Epoch 323/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1265 - accuracy: 0.7500
Epoch 324/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1271 - accuracy: 0.7500
Epoch 325/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1275 - accuracy: 0.5000
Epoch 326/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1264 - accuracy: 0.5000
Epoch 327/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1273 - accuracy: 0.5000
Epoch 328/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1263 - accuracy: 0.7500
Epoch 329/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1262 - accuracy: 0.7500
Epoch 330/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1262 - accuracy: 0.

4/4 [==============================] - 0s 2ms/sample - loss: 0.1264 - accuracy: 0.7500
Epoch 402/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1263 - accuracy: 0.5000
Epoch 403/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1262 - accuracy: 0.7500
Epoch 404/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1271 - accuracy: 0.5000
Epoch 405/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1261 - accuracy: 0.7500
Epoch 406/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1261 - accuracy: 0.7500
Epoch 407/1000
4/4 [==============================] - 0s 997us/sample - loss: 0.1264 - accuracy: 0.5000
Epoch 408/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1262 - accuracy: 0.7500
Epoch 409/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1263 - accuracy: 0.7500
Epoch 410/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1277 - accuracy: 

4/4 [==============================] - 0s 1ms/sample - loss: 0.1272 - accuracy: 0.5000
Epoch 482/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1261 - accuracy: 0.7500
Epoch 483/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1262 - accuracy: 0.7500
Epoch 484/1000
4/4 [==============================] - 0s 997us/sample - loss: 0.1261 - accuracy: 0.5000
Epoch 485/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1270 - accuracy: 0.5000
Epoch 486/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1262 - accuracy: 0.5000
Epoch 487/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1269 - accuracy: 0.5000
Epoch 488/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1263 - accuracy: 0.7500
Epoch 489/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1268 - accuracy: 0.7500
Epoch 490/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1271 - accuracy: 

4/4 [==============================] - 0s 2ms/sample - loss: 0.1265 - accuracy: 0.7500
Epoch 562/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1275 - accuracy: 0.7500
Epoch 563/1000
4/4 [==============================] - 0s 3ms/sample - loss: 0.1260 - accuracy: 0.5000
Epoch 564/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1272 - accuracy: 0.7500
Epoch 565/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1267 - accuracy: 0.7500
Epoch 566/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1261 - accuracy: 0.7500
Epoch 567/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1265 - accuracy: 0.7500
Epoch 568/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1268 - accuracy: 0.7500
Epoch 569/1000
4/4 [==============================] - 0s 997us/sample - loss: 0.1257 - accuracy: 0.7500
Epoch 570/1000
4/4 [==============================] - 0s 997us/sample - loss: 0.1264 - accuracy

4/4 [==============================] - 0s 3ms/sample - loss: 0.1275 - accuracy: 0.7500
Epoch 642/1000
4/4 [==============================] - 0s 5ms/sample - loss: 0.1270 - accuracy: 0.5000
Epoch 643/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1278 - accuracy: 0.5000
Epoch 644/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1271 - accuracy: 0.7500
Epoch 645/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1266 - accuracy: 0.7500
Epoch 646/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1257 - accuracy: 0.7500
Epoch 647/1000
4/4 [==============================] - 0s 3ms/sample - loss: 0.1260 - accuracy: 0.7500
Epoch 648/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1276 - accuracy: 0.5000
Epoch 649/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1265 - accuracy: 0.5000
Epoch 650/1000
4/4 [==============================] - 0s 3ms/sample - loss: 0.1272 - accuracy: 0.

4/4 [==============================] - 0s 2ms/sample - loss: 0.1272 - accuracy: 0.7500
Epoch 722/1000
4/4 [==============================] - 0s 3ms/sample - loss: 0.1260 - accuracy: 0.5000
Epoch 723/1000
4/4 [==============================] - 0s 3ms/sample - loss: 0.1259 - accuracy: 0.7500
Epoch 724/1000
4/4 [==============================] - 0s 3ms/sample - loss: 0.1259 - accuracy: 0.7500
Epoch 725/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1265 - accuracy: 0.7500
Epoch 726/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1263 - accuracy: 0.7500
Epoch 727/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1261 - accuracy: 0.5000
Epoch 728/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1268 - accuracy: 0.5000
Epoch 729/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1261 - accuracy: 0.5000
Epoch 730/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1276 - accuracy: 0.

4/4 [==============================] - 0s 2ms/sample - loss: 0.1263 - accuracy: 0.7500
Epoch 802/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1258 - accuracy: 0.7500
Epoch 803/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1261 - accuracy: 0.5000
Epoch 804/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1260 - accuracy: 0.7500
Epoch 805/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1259 - accuracy: 0.7500
Epoch 806/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1270 - accuracy: 0.5000
Epoch 807/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1259 - accuracy: 0.7500
Epoch 808/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1261 - accuracy: 0.5000
Epoch 809/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1268 - accuracy: 0.7500
Epoch 810/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1258 - accuracy: 0.

4/4 [==============================] - 0s 2ms/sample - loss: 0.1259 - accuracy: 0.5000
Epoch 882/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1277 - accuracy: 0.5000
Epoch 883/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1265 - accuracy: 0.7500
Epoch 884/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1268 - accuracy: 0.7500
Epoch 885/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1256 - accuracy: 0.7500
Epoch 886/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1264 - accuracy: 0.7500
Epoch 887/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1261 - accuracy: 0.5000
Epoch 888/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1259 - accuracy: 0.5000
Epoch 889/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1266 - accuracy: 0.5000
Epoch 890/1000
4/4 [==============================] - 0s 2ms/sample - loss: 0.1258 - accuracy: 0.

4/4 [==============================] - 0s 1ms/sample - loss: 0.1262 - accuracy: 0.7500
Epoch 961/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1275 - accuracy: 0.7500
Epoch 962/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1265 - accuracy: 0.7500
Epoch 963/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1263 - accuracy: 0.7500
Epoch 964/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1256 - accuracy: 0.7500
Epoch 965/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1262 - accuracy: 0.7500
Epoch 966/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1263 - accuracy: 0.7500
Epoch 967/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1258 - accuracy: 0.5000
Epoch 968/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1261 - accuracy: 0.7500
Epoch 969/1000
4/4 [==============================] - 0s 1ms/sample - loss: 0.1260 - accuracy: 0.

In [5]:
preds = model.predict(x_train)
np.round(preds)

array([[0.],
       [1.],
       [0.],
       [0.]], dtype=float32)

In [6]:
model.evaluate(x_train,y_train)  # [0.00010335762635804713, 1.0]

4/1 [========================================================================================================================] - 0s 20ms/sample - loss: 0.1251 - accuracy: 0.7500


[0.1250535547733307, 0.75]

In [7]:
# X,Y input data 
x_train = np.array([[1.0,   2.0,  3.0,  4.0,  5.0],
                    [6.0,   7.0,  8.0,  9.0, 10.0],
                    [11.0, 12.0, 13.0, 14.0, 15.0]])  # (3,5)
                    
                    
y_train = np.array([[1.1,   2.2,  3.3,  4.4,  5.5],
                    [6.1,   7.2,  8.3,  9.4, 10.5],
                    [11.1, 12.2, 13.3, 14.4, 15.5]]) # (3,5)

model = tf.keras.Sequential([
    # (3,1) * (1,100) = (3,100)   , Param :200 (W:1*100, b:100), (1 + 1) * 100 = 200
    # tf.keras.layers.Dense(units=100, activation='relu', input_shape=(1,)), # input data의 shape을 (?,1) 

    # (3,5) * (5,100) = (3,100)   , Param :600 (W:5*100, b:100), (5 + 1) * (100) = 600
    tf.keras.layers.Dense(units=100, activation='relu', input_shape=(5,)), # input data의 shape을 (?,5) 

    
    # (3,100) * (100,50) = (3,50)   , Param : 5050 (W:100*50, b:50), (100+1)*50 = 5050
    tf.keras.layers.Dense(units=50, activation='relu' ), 
    
    # (3,50) * (50,25) = (3,25)   , Param : 1275 (W:50*25, b:25), (50 + 1)* 25 = 1275
    tf.keras.layers.Dense(units=25, activation='relu' ),
    
    # (3,25) * (25,5) = (3,5)   , Param : 130 (W:25*5, b:5), (25 + 1) * 5 = 130
    tf.keras.layers.Dense(units=5 , activation='relu' ),
    
#     # (3,5) * (5,1) = (3,1)   , Pram : 6  (W:5*1, b:1), (5 + 1) *1 = 6
#     tf.keras.layers.Dense(units=1)
])

model.compile(optimizer=tf.keras.optimizers.Adam(lr=0.01), loss='mse')

model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_2 (Dense)              (None, 100)               600       
_________________________________________________________________
dense_3 (Dense)              (None, 50)                5050      
_________________________________________________________________
dense_4 (Dense)              (None, 25)                1275      
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 130       
Total params: 7,055
Trainable params: 7,055
Non-trainable params: 0
_________________________________________________________________


In [8]:
model.fit(x_train, y_train, epochs=100)

Train on 3 samples
Epoch 1/100
3/3 [==============================] - 0s 139ms/sample - loss: 78.1356
Epoch 2/100
3/3 [==============================] - 0s 665us/sample - loss: 55.7781
Epoch 3/100
3/3 [==============================] - 0s 665us/sample - loss: 46.8733
Epoch 4/100
3/3 [==============================] - 0s 665us/sample - loss: 47.7416
Epoch 5/100
3/3 [==============================] - 0s 997us/sample - loss: 47.4192
Epoch 6/100
3/3 [==============================] - 0s 665us/sample - loss: 45.4409
Epoch 7/100
3/3 [==============================] - 0s 665us/sample - loss: 45.1841
Epoch 8/100
3/3 [==============================] - 0s 664us/sample - loss: 45.2659
Epoch 9/100
3/3 [==============================] - 0s 665us/sample - loss: 44.9496
Epoch 10/100
3/3 [==============================] - 0s 665us/sample - loss: 44.2379
Epoch 11/100
3/3 [==============================] - 0s 663us/sample - loss: 43.6650
Epoch 12/100
3/3 [==============================] - 0s 333us/sampl

Epoch 99/100
3/3 [==============================] - 0s 332us/sample - loss: 42.4949
Epoch 100/100
3/3 [==============================] - 0s 998us/sample - loss: 42.4949


In [9]:
model.predict(x_train)

array([[ 1.0682873,  2.1898782,  0.       ,  4.426662 ,  0.       ],
       [ 6.118274 ,  7.1831346,  0.       ,  9.386575 ,  0.       ],
       [11.1018505, 12.174786 ,  0.       , 14.417199 ,  0.       ]],
      dtype=float32)

In [10]:
model.evaluate(x_train,y_train)

3/1 [==========================================================================================] - 0s 16ms/sample - loss: 42.4949


42.494903564453125

### [2] Flatten Layer

In [11]:
# 4차원 데이터를 2차원으로 축소하여 FC Layer에 전달
data = np.arange(1000*28*28*10).reshape(1000,28,28,10).astype(np.float32)
print(data.shape) # (None, 28, 28, 10)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (None, 28*28*10) = (None,7840)

(1000, 28, 28, 10)
(1000, 7840)


In [12]:
# 3차원 데이터를 2차원으로 축소하여 FC Layer에 전달
data = np.arange(1000*28*28).reshape(1000,28,28).astype(np.float32)
print(data.shape) # (None, 28, 28)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (None, 28*28) = (None,784)

(1000, 28, 28)
(1000, 784)


In [13]:
# 2차원 데이터는 그대로 2차원으로 FC Layer에 전달
data = np.arange(28*28).reshape(28,28).astype(np.float32)
print(data.shape) # (28, 28)
layer = tf.keras.layers.Flatten()
outputs = layer(data)
print(outputs.shape) # (28,28) 

(28, 28)
(28, 28)


### [3] Dropout Layer

In [14]:
# https://www.tensorflow.org/api_docs/python/tf/keras/layers/Dropout
# The Dropout layer randomly sets input units to 0 with a frequency of rate 
# at each step during training time, which helps prevent overfitting. 
# Inputs not set to 0 are scaled up by 1/(1 - rate) such that the sum over all inputs is unchanged.

# Note that the Dropout layer only applies when training is set to True such that
# no values are dropped during inference. When using model.fit, training will be
# appropriately set to True automatically, and in other contexts, you can set 
# the kwarg explicitly to True when calling the layer.

# (This is in contrast to setting trainable=False for a Dropout layer.
# trainable does not affect the layer's behavior, as Dropout does not have any 
# variables/weights that can be frozen during training.)

In [15]:
# 신버전 keras dropout

tf.random.set_seed(0)
data = np.arange(10).reshape(5,2).astype(np.float32)
print(data)

layer = tf.keras.layers.Dropout(0.3,input_shape=(2,))

outputs = layer(data,training=True)
# model.fit()호출 시는  학습 모드로 training=True가 되어 dropuout 적용
# model.evaluate() 호출 시는 예측 모드로 False가 되어 dropuout이 수행되지 않음
print(outputs) # 데이터의 30%는 0으로 나머지 데이터는  1/(1-0.3)으로 곱하여 scaled up된다
print(data*1/(1 - 0.3))

[[0. 1.]
 [2. 3.]
 [4. 5.]
 [6. 7.]
 [8. 9.]]
tf.Tensor(
[[ 0.         0.       ]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.1428576]
 [ 8.571428  10.       ]
 [11.428572   0.       ]], shape=(5, 2), dtype=float32)
[[ 0.         1.4285715]
 [ 2.857143   4.285714 ]
 [ 5.714286   7.142857 ]
 [ 8.571428  10.       ]
 [11.428572  12.857143 ]]


In [16]:
# 구버전 dropout : 사용이 번거로움
tf.random.set_seed(0)

data = np.arange(10).reshape(5,2).astype(np.float32)

def layer1(X,dr_rate):
    return tf.nn.dropout(X,rate=dr_rate)

layer1(data,dr_rate=0.3)    

<tf.Tensor: id=16120, shape=(5, 2), dtype=float32, numpy=
array([[ 0.       ,  0.       ],
       [ 2.857143 ,  4.285714 ],
       [ 5.714286 ,  7.1428576],
       [ 8.571428 , 10.       ],
       [11.428572 ,  0.       ]], dtype=float32)>